permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Aaron Zhu
  email: zqwchen6@126.com
  link: http://zhuquanwu.com
  weibo: http://weibo.com/qwzhu
  github: http://github.com/Aaron-Zhu
  zhihu: http://www.zhihu.com/people/zhu-quan-wu
  linkedin: http://www.linkedin.com/profile/view?id=372010893&trk=hp-identity-name

# 站点信息
title: 朱全武的博客
description: My personal blog
url: http://zhuquanwu.com
rss_url: /pages/atom.xml


# google analytics 设置
ga:
  id: UA-54262064-1 
  url: zhuquanwu.com

# disqus 设置
disqus:
  shortname: Aaron-Zhu

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
